// flow-typed signature: cd85fbd2a165b557ce19bb97747384ce
// flow-typed version: <<STUB>>/react-redux-mock_v^0.2.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-mock/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux-mock/src/index' {
  declare module.exports: any;
}

declare module 'react-redux-mock/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-mock/lib/index.js' {
  declare module.exports: $Exports<'react-redux-mock/lib/index'>;
}
declare module 'react-redux-mock/src/index.js' {
  declare module.exports: $Exports<'react-redux-mock/src/index'>;
}
declare module 'react-redux-mock/webpack.config.js' {
  declare module.exports: $Exports<'react-redux-mock/webpack.config'>;
}
